SET DEFINE OFF;

-- Optional: quick check before insert (should be 0)
SELECT COUNT(*) AS existing_rows
FROM LDM.CORR_LAW_MKP_LDM
WHERE LAW_ID IN (
  35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,54,56,58,60,62,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91
);

INSERT ALL
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (35, 'US-VA', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (36, 'KR',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (37, 'PL',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (38, 'NL',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (39, 'FI',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (40, 'SE',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (41, 'US-PA', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (42, 'US-UT', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (43, 'IM',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (44, 'US-WA', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (45, 'US-IL', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (46, 'US-OK', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (47, 'LU',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (48, 'AU-WA', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (49, 'US-LA', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (50, 'AT',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (51, 'RU',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (52, 'US-CO', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)

  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (54, 'US-KY', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (56, 'US-ME', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (58, 'US-MI', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)

  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (60, 'CA-SK', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (62, 'CA-MB', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)

  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (64, 'US-WI', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (65, 'US-FL', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (66, 'US-IN', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (67, 'US-MB', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (68, 'US-MN', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (69, 'US-NE', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (70, 'US-OH', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (71, 'US-AL', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (72, 'US-MO', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)

  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (73, 'BR',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (74, 'US-ND', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (75, 'US-GA', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (76, 'TH',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (77, 'US-NM', TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)

  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (78, 'CZ',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (79, 'NO',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (80, 'MY',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (81, 'CO',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (82, 'AR',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (83, 'VN',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (84, 'ID',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (85, 'IL',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (86, 'MX',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (87, 'DK',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (88, 'GB-SCT',TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (89, 'HU',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (90, 'GR',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
  INTO LDM.CORR_LAW_MKP_LDM (LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF) VALUES (91, 'MC',    TO_DATE('2026-02-19','YYYY-MM-DD'), 'BEADEV-10710', NULL, NULL)
SELECT 1 FROM DUAL;

COMMIT;

-- Optional: verify
SELECT LAW_ID, LAW_COD, DATE_CREAT, USER_CREAT, DATE_MODIF, USER_MODIF
FROM LDM.CORR_LAW_MKP_LDM
WHERE LAW_ID IN (
  35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,54,56,58,60,62,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91
)
ORDER BY LAW_ID;